var Products = {
    "beer": [
        {
            "nr": "1004703",
            "articleid": "723841",
            "articletype": "10047",
            "name": "Nils Oscar",
            "name2": "Celebration Ale",
            "priceinclvat": "43.70",
            "volumeml": null,
            "priceperlitre": null,
            "introduced": "2013-02-01",
            "finaldelivery": " ",
            "catgegory": "Ã–l, Ale",
            "packaging": "Flaska",
            "captype": "",
            "countryoforigin": "",
            "countryoforiginlandname": "Sverige",
            "producer": "Nils Oscar Company",
            "provider": "The Nils Oscar Company AB",
            "productionyear": "",
            "testedproductionyear": "",
            "alcoholstrength": "9.4%",
            "module": "T5",
            "assortment": "TSE",
            "organic": "0",
            "kosher": "0",
            "available": "true",
            "curprice": "0"
        },
        {
            "nr": "1101003",
            "articleid": "665836",
            "articletype": "11010",
            "name": "Corsendonk Christmas Ale",
            "name2": "",
            "priceinclvat": "20.90",
            "volumeml": null,
            "priceperlitre": null,
            "introduced": "2012-11-15",
            "finaldelivery": " ",
            "catgegory": "Ã–l, Ale",
            "packaging": "Flaska",
            "captype": "",
            "countryoforigin": "",
            "countryoforiginlandname": "Belgien",
            "producer": "Brouwerij Corsendonk",
            "provider": "AB Wicked Wine Sweden",
            "productionyear": "",
            "testedproductionyear": "",
            "alcoholstrength": "8.1%",
            "module": "",
            "assortment": "TSS",
            "organic": "0",
            "kosher": "0",
            "available": "true",
            "curprice": "0"
        },
        {
            "nr": "1101203",
            "articleid": "766235",
            "articletype": "11012",
            "name": "Flying Dog",
            "name2": "K-9 Cruiser Winter Ale",
            "priceinclvat": "27.30",
            "volumeml": null,
            "priceperlitre": null,
            "introduced": "2013-11-15",
            "finaldelivery": " ",
            "catgegory": "Ã–l, Ale",
            "packaging": "Flaska",
            "captype": "",
            "countryoforigin": "",
            "countryoforiginlandname": "USA",
            "producer": "Flying Dog Brewery",
            "provider": "AB Wicked Wine Sweden",
            "productionyear": "",
            "testedproductionyear": "",
            "alcoholstrength": "7.4%",
            "module": "",
            "assortment": "TSS",
            "organic": "0",
            "kosher": "0",
            "available": "true",
            "curprice": "0"
        },
        {
            "nr": "1104303",
            "articleid": "721432",
            "articletype": "11043",
            "name": "Omnipollo Nebuchadnezzar",
            "name2": "",
            "priceinclvat": "39.90",
            "volumeml": null,
            "priceperlitre": null,
            "introduced": "2013-02-01",
            "finaldelivery": " ",
            "catgegory": "Ã–l, Ale",
            "packaging": "Flaska",
            "captype": "",
            "countryoforigin": "",
            "countryoforiginlandname": "Internationellt mÃ¤rke",
            "producer": "Omnipollo",
            "provider": "Brill & Co AB",
            "productionyear": "",
            "testedproductionyear": "",
            "alcoholstrength": "8.5%",
            "module": "",
            "assortment": "TSE",
            "organic": "0",
            "kosher": "0",
            "available": "true",
            "curprice": "0"
        },
        {
            "nr": "1104712",
            "articleid": "721994",
            "articletype": "11047",
            "name": "Deviant Dale's",
            "name2": "India Pale Ale",
            "priceinclvat": "54.90",
            "volumeml": null,
            "priceperlitre": null,
            "introduced": "2013-03-01",
            "finaldelivery": " ",
            "catgegory": "Ã–l, Ale",
            "packaging": "Burk",
            "captype": "",
            "countryoforigin": "",
            "countryoforiginlandname": "USA",
            "producer": "Oskar Blues Brewery",
            "provider": "Great Brands AB",
            "productionyear": "",
            "testedproductionyear": "",
            "alcoholstrength": "8%",
            "module": "",
            "assortment": "TSE",
            "organic": "0",
            "kosher": "0",
            "available": "true",
            "curprice": "0"
        }
    ],
    "wine": [
        {
            "nr": "1123401",
            "articleid": "543793",
            "articletype": "11234",
            "name": "Kiviks Ã„ppelvin",
            "name2": "Halvtorrt",
            "priceinclvat": "69.00",
            "volumeml": null,
            "priceperlitre": null,
            "introduced": "2011-04-01",
            "finaldelivery": " ",
            "catgegory": "Fruktvin, Torrt",
            "packaging": "Flaska",
            "captype": "Skruvkapsyl",
            "countryoforigin": "SkÃ¥ne lÃ¤n, Simrishamns kommun",
            "countryoforiginlandname": "Sverige",
            "producer": "Kiviks Musteri AB",
            "provider": "Kiviks Musteri AB",
            "productionyear": "",
            "testedproductionyear": "",
            "alcoholstrength": "10%",
            "module": "",
            "assortment": "FS",
            "organic": "0",
            "kosher": "0",
            "available": "true",
            "curprice": "0"
        },
        {
            "nr": "1128201",
            "articleid": "544208",
            "articletype": "11282",
            "name": "Mandorla",
            "name2": "Negroamaro Rosato",
            "priceinclvat": "59.00",
            "volumeml": null,
            "priceperlitre": null,
            "introduced": "2011-04-01",
            "finaldelivery": " ",
            "catgegory": "RosÃ©vin",
            "packaging": "Flaska",
            "captype": "Skruvkapsyl",
            "countryoforigin": "Apulien, Salento",
            "countryoforiginlandname": "Italien",
            "producer": "Wine World Producer",
            "provider": "Mondo Wine Sweden AB",
            "productionyear": "2012",
            "testedproductionyear": "",
            "alcoholstrength": "12.5%",
            "module": "",
            "assortment": "BS",
            "organic": "0",
            "kosher": "0",
            "available": "true",
            "curprice": "0"
        },
        {
            "nr": "1200001",
            "articleid": "190680",
            "articletype": "12000",
            "name": "Vicar's Choice",
            "name2": "Sauvignon Blanc",
            "priceinclvat": "89.00",
            "volumeml": null,
            "priceperlitre": null,
            "introduced": "2006-04-01",
            "finaldelivery": " ",
            "catgegory": "Vitt vin,  Friskt & Fruktigt",
            "packaging": "Flaska",
            "captype": "Skruvkapsyl",
            "countryoforigin": "Marlborough",
            "countryoforiginlandname": "Nya Zeeland",
            "producer": "Saint Clair Family Estate",
            "provider": "Sigva AB",
            "productionyear": "2013",
            "testedproductionyear": "2013",
            "alcoholstrength": "13%",
            "module": "",
            "assortment": "FS",
            "organic": "0",
            "kosher": "0",
            "available": "true",
            "curprice": "0"
        },
        {
            "nr": "1200002",
            "articleid": "368629",
            "articletype": "12000",
            "name": "Vicar's Choice",
            "name2": "Sauvignon Blanc",
            "priceinclvat": "49.00",
            "volumeml": null,
            "priceperlitre": null,
            "introduced": "2009-04-01",
            "finaldelivery": " ",
            "catgegory": "Vitt vin,  Friskt & Fruktigt",
            "packaging": "Flaska",
            "captype": "Skruvkapsyl",
            "countryoforigin": "Marlborough",
            "countryoforiginlandname": "Nya Zeeland",
            "producer": "Saint Clair Family Estate",
            "provider": "Sigva AB",
            "productionyear": "2013",
            "testedproductionyear": "2013",
            "alcoholstrength": "13%",
            "module": "",
            "assortment": "FS",
            "organic": "0",
            "kosher": "0",
            "available": "true",
            "curprice": "0"
        },
        {
            "nr": "1200201",
            "articleid": "33861",
            "articletype": "12002",
            "name": "Allesverloren",
            "name2": "Tinta Barocca",
            "priceinclvat": "125.00",
            "volumeml": null,
            "priceperlitre": null,
            "introduced": "2002-04-02",
            "finaldelivery": " ",
            "catgegory": "RÃ¶tt vin, Kryddigt & Mustigt",
            "packaging": "Flaska",
            "captype": "Naturkork",
            "countryoforigin": "Western Cape, Coastal Region, Swartland",
            "countryoforiginlandname": "Sydafrika",
            "producer": "Allesverloren Wine Estate",
            "provider": "janake wine group AB",
            "productionyear": "2012",
            "testedproductionyear": "2012",
            "alcoholstrength": "14%",
            "module": "",
            "assortment": "FS",
            "organic": "0",
            "kosher": "0",
            "available": "true",
            "curprice": "0"
        }
    ],
    "cocktail": [
        {
            "nr": "1101502",
            "articleid": "667645",
            "articletype": "11015",
            "name": "Xide Winter",
            "name2": "Tangelo & Ginger",
            "priceinclvat": "17.90",
            "volumeml": null,
            "priceperlitre": null,
            "introduced": "2012-11-15",
            "finaldelivery": " ",
            "catgegory": "Blanddrycker",
            "packaging": "Flaska",
            "captype": "",
            "countryoforigin": "Kronobergs lÃ¤n, Tingsryds kommun",
            "countryoforiginlandname": "Sverige",
            "producer": "Carlsberg Sverige AB",
            "provider": "Carlsberg Sverige AB",
            "productionyear": "",
            "testedproductionyear": "",
            "alcoholstrength": "4.5%",
            "module": "",
            "assortment": "TSS",
            "organic": "0",
            "kosher": "0",
            "available": "true",
            "curprice": "0"
        },
        {
            "nr": "1184503",
            "articleid": "719766",
            "articletype": "11845",
            "name": "Xide Cactus Lime",
            "name2": "",
            "priceinclvat": "15.90",
            "volumeml": null,
            "priceperlitre": null,
            "introduced": "2013-04-02",
            "finaldelivery": " ",
            "catgegory": "Blanddrycker",
            "packaging": "Flaska",
            "captype": "",
            "countryoforigin": "Hallands lÃ¤n, Falkenbergs kommun",
            "countryoforiginlandname": "Sverige",
            "producer": "Carlsberg Sverige AB",
            "provider": "Carlsberg Sverige AB",
            "productionyear": "",
            "testedproductionyear": "",
            "alcoholstrength": "4.5%",
            "module": "",
            "assortment": "FS",
            "organic": "0",
            "kosher": "0",
            "available": "true",
            "curprice": "0"
        },
        {
            "nr": "170102",
            "articleid": "707123",
            "articletype": "1701",
            "name": "Ã…kesson Winecooler",
            "name2": "Sauvignon Blanc",
            "priceinclvat": "18.90",
            "volumeml": null,
            "priceperlitre": null,
            "introduced": "2013-03-01",
            "finaldelivery": " ",
            "catgegory": "Blanddrycker",
            "packaging": "Flaska",
            "captype": "",
            "countryoforigin": "",
            "countryoforiginlandname": "Sverige",
            "producer": "Kiviks Musteri AB",
            "provider": "Kiviks Musteri AB",
            "productionyear": "",
            "testedproductionyear": "",
            "alcoholstrength": "4.5%",
            "module": "",
            "assortment": "BS",
            "organic": "0",
            "kosher": "0",
            "available": "true",
            "curprice": "0"
        },
        {
            "nr": "170702",
            "articleid": "434810",
            "articletype": "1707",
            "name": "Bacardi Breezer",
            "name2": "Orange",
            "priceinclvat": "19.90",
            "volumeml": null,
            "priceperlitre": null,
            "introduced": "2010-03-24",
            "finaldelivery": " ",
            "catgegory": "Blanddrycker",
            "packaging": "Flaska",
            "captype": "",
            "countryoforigin": "",
            "countryoforiginlandname": "Internationellt mÃ¤rke",
            "producer": "Bacardi",
            "provider": "Bacardi AB",
            "productionyear": "",
            "testedproductionyear": "",
            "alcoholstrength": "4%",
            "module": "",
            "assortment": "FS",
            "organic": "0",
            "kosher": "0",
            "available": "true",
            "curprice": "0"
        },
        {
            "nr": "171601",
            "articleid": "670213",
            "articletype": "1716",
            "name": "Jeremiah Weed",
            "name2": "Sour Mash Brew",
            "priceinclvat": "24.90",
            "volumeml": null,
            "priceperlitre": null,
            "introduced": "2012-10-01",
            "finaldelivery": " ",
            "catgegory": "Blanddrycker",
            "packaging": "Flaska",
            "captype": "",
            "countryoforigin": "",
            "countryoforiginlandname": "Internationellt mÃ¤rke",
            "producer": "Diageo Plc",
            "provider": "Carlsberg Sverige AB",
            "productionyear": "",
            "testedproductionyear": "",
            "alcoholstrength": "4%",
            "module": "",
            "assortment": "FSN",
            "organic": "0",
            "kosher": "0",
            "available": "true",
            "curprice": "0"
        }
    ],
    "dishes": [
        {
            "nr": "10001",
            "articleid": "25053",
            "articletype": "100",
            "name": "Braastad XO",
            "name2": "",
            "priceinclvat": "442.00",
            "volumeml": null,
            "priceperlitre": null,
            "introduced": "2000-08-07",
            "finaldelivery": " ",
            "catgegory": "Cognac",
            "packaging": "Flaska",
            "captype": "Naturkork",
            "countryoforigin": "Cognac, Fine Champagne",
            "countryoforiginlandname": "Frankrike",
            "producer": "Tiffon",
            "provider": "Arcus Sweden AB",
            "productionyear": "",
            "testedproductionyear": "",
            "alcoholstrength": "40%",
            "module": "",
            "assortment": "FS",
            "organic": "0",
            "kosher": "0",
            "available": "true",
            "curprice": "0"
        },
        {
            "nr": "1001",
            "articleid": "190719",
            "articletype": "10",
            "name": "Vanlig Vodka",
            "name2": "",
            "priceinclvat": "195.00",
            "volumeml": null,
            "priceperlitre": null,
            "introduced": "2006-04-01",
            "finaldelivery": " ",
            "catgegory": "Okryddad sprit",
            "packaging": "Flaska",
            "captype": "Skruvkapsyl",
            "countryoforigin": "",
            "countryoforiginlandname": "Sverige",
            "producer": "Svensk Export Vodka AB",
            "provider": "Fondberg",
            "productionyear": "",
            "testedproductionyear": "",
            "alcoholstrength": "37.5%",
            "module": "",
            "assortment": "FS",
            "organic": "0",
            "kosher": "0",
            "available": "true",
            "curprice": "0"
        },
        {
            "nr": "1001201",
            "articleid": "51029",
            "articletype": "10012",
            "name": "Dworek Vodka",
            "name2": "",
            "priceinclvat": "190.00",
            "volumeml": null,
            "priceperlitre": null,
            "introduced": "2004-12-06",
            "finaldelivery": " ",
            "catgegory": "Okryddad sprit",
            "packaging": "Flaska",
            "captype": "",
            "countryoforigin": "",
            "countryoforiginlandname": "Polen",
            "producer": "Tarpan Fabryka Likierow",
            "provider": "TIWA Trading AB",
            "productionyear": "",
            "testedproductionyear": "",
            "alcoholstrength": "37.5%",
            "module": "",
            "assortment": "FS",
            "organic": "0",
            "kosher": "0",
            "available": "true",
            "curprice": "0"
        },
        {
            "nr": "1001202",
            "articleid": "407506",
            "articletype": "10012",
            "name": "Dworek Vodka",
            "name2": "",
            "priceinclvat": "100.00",
            "volumeml": null,
            "priceperlitre": null,
            "introduced": "2009-10-01",
            "finaldelivery": " ",
            "catgegory": "Okryddad sprit",
            "packaging": "Flaska",
            "captype": "Skruvkapsyl",
            "countryoforigin": "",
            "countryoforiginlandname": "Polen",
            "producer": "Tarpan Fabryka Likierow",
            "provider": "TIWA Trading AB",
            "productionyear": "",
            "testedproductionyear": "",
            "alcoholstrength": "37.5%",
            "module": "",
            "assortment": "FS",
            "organic": "0",
            "kosher": "0",
            "available": "true",
            "curprice": "0"
        },
        {
            "nr": "1003802",
            "articleid": "513291",
            "articletype": "10038",
            "name": "Esping Jul BÃ¤sk",
            "name2": "",
            "priceinclvat": "195.00",
            "volumeml": null,
            "priceperlitre": null,
            "introduced": "2010-11-15",
            "finaldelivery": " ",
            "catgegory": "Kryddad sprit",
            "packaging": "Flaska",
            "captype": "",
            "countryoforigin": "",
            "countryoforiginlandname": "Sverige",
            "producer": "Symposion International",
            "provider": "Symposion International AB",
            "productionyear": "",
            "testedproductionyear": "",
            "alcoholstrength": "32%",
            "module": "",
            "assortment": "TSS",
            "organic": "0",
            "kosher": "0",
            "available": "true",
            "curprice": "0"
        }
    ]
}

var Tables = {
    "table1": [
    {
        "orders": ["test","test2"],
        "sum": 0
    }
],
    "table2": [
    {
        "orders": [],
        "sum": 0
    }
],
    "table3": [
    {
        "orders": [],
        "sum": 0
    }
],
    "table4": [
    {
        "orders": [],
        "sum": 0
    }
]
}

var testJSON = {
    "tables" : 
        [
          {"table#": "1","sum":"0", "orders":[]},
          {"table#": "2", "sum":"0", "orders":[]},
          {"table#": "3", "sum":"0", "orders":[]},
          {"table#": "4", "sum":"0", "orders":[]}
        ]
}

var testDB = '{"tables":[' +
'{"order":"John","sum":"0" },' +
'{"order":"Anna","sum":"100" },' +
'{"order":"Peter","sum":200 }]}';

var language = {
    'english': [
        {'Tablebutton' : 'Tables'},
        {'Productbutton' : 'Products'}
    ],
    'swedish': [
        {'Tablebutton' : 'Bord'},
        {'Productbutton' : 'Produkter'} 
    ]
    }